### ISSUE TITLE
Better styling of errors

### ISSUE THREAD

**Issue by iandees** [RagtagOpen/mustachify#20]
Right now, the error messages ("flashes") are shown in an unordered list that is unstyled:

![image](https://user-images.githubusercontent.com/261584/34910821-89dbe5a0-f882-11e7-9136-e3dbd63b8446.png)

**Comment by schloo** [comment]
Styles updated!

**Comment by iandees** [comment]
Fixed in 5a2cb5f738d481ac48895c8e2d65de0d94a7e124.
