### ISSUE TITLE
Change color of spinner to match button

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/mustachify#27]
The spinner should probably match the color of the buttons -- it might already match, but I couldn't tell because in the screencap, the upload button must be in a lighter-blue focus/hover state while the upload is happening. Just in case, here's a gif with the right color (#2358ca):

**Comment by bnd5k** [comment]
Spinner already uses #2358ca. 👍

**Comment by iandees** [comment]
So can we close this, @bnd5k ?

**Comment by bnd5k** [comment]
Yep.
