### ISSUE TITLE
Make buttons look unclickable during image upload/mustachification

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/mustachify#28]
Right now the buttons still look clickable while the image is uploading. Ideally I think we'd reduce the opacity of the entire contents of .form-box (or put a white overlay with ~0.6 opacity over it) so that it looks less active, and move the spinner up so it looks more like an overlay. And we'd probably disable the button accordingly.

**Comment by bnd5k** [comment]
PR: https://github.com/RagtagOpen/mustachify/pull/29
