### ISSUE TITLE
Image gets half-mustache

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/mustachify#31]
Original image and result

![bryson jones_nc79_vertical](https://user-images.githubusercontent.com/2319837/35757397-ac8cf05c-0823-11e8-9851-d6d7630e9f53.jpeg)
![gxi2y2eftjcm0ab3qxsw6w](https://user-images.githubusercontent.com/2319837/35757406-b25c9848-0823-11e8-9cb6-2d83a4892062.jpeg)

**Comment by iandees** [comment]
This is related to #13. In this case the original is tall enough to hold the mustache original but not wide enough, so my check that I added to fix #13 doesn't work.

We should resize the image to our target size and then operate on the smaller image. That'll make it more certain we handle the mustache rotation properly.
