### ISSUE TITLE
Photo didn't get a mustache at all

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/mustachify#39]
But also didn't get an error message.
![screen shot 2017-11-13 at 11 31 24 am](https://user-images.githubusercontent.com/2319837/36648438-926992f2-1a48-11e8-8b5d-52dea6b29295.png)

**Comment by iandees** [comment]
This is because it detects your face as being tilted too much. It says 34° and I had set the limit to 30°, so I'm going to bump it to 35°.
