### ISSUE TITLE
Mustache not placed right on 3/4 profile pic

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/mustachify#40]
Using Safari 11.0.2 13604.4.7.1.3 on macOS 10.13.2

Stache appears to center on the bump of my nostril

Shadow on my face probably messing with it?

![3duxdku5qgilsxzprutyuw](https://user-images.githubusercontent.com/32378726/36648542-a90a6486-1a49-11e8-9256-1546c83f821a.jpg)
![mediumblog](https://user-images.githubusercontent.com/32378726/36648544-ac58dc94-1a49-11e8-92f3-5457354670f5.jpg)

**Comment by iandees** [comment]
This might be because the detected nose point was too high. Also, the mouth corners are really high. You're smiling too much!

To help make this better, I think we need to set the target width for the mustache to be wider than the mouth rather than exactly the width of the mouth.

**Comment by iandees** [comment]
With #47 I think this is at least adjustable. The number I put in there for now is 25%, but it could probably be even bigger. This doesn't solve the problem of the mustache seemingly starting from the nose, which I don't think I can solve with the data we get from Rekognize.

**Comment by dryan** [comment]
I'm closing this out in favor of #47 which will address the parts of this we can address.
