### ISSUE TITLE
Mustache placed properly, did not scale

### ISSUE THREAD

**Issue by nlistgarten** [RagtagOpen/mustachify#41]
Mustache appears to be placed properly, but did not appear to scale properly.

Mustachiofied:
![image](https://user-images.githubusercontent.com/4617556/36648595-7cd3ad72-1a63-11e8-8b01-d0113ad74545.png)

Original:
![img_3888](https://user-images.githubusercontent.com/4617556/36648580-5443f524-1a63-11e8-8150-f96c723cec0d.JPG)

**Comment by dryan** [comment]
![_2dblgjrta61y2-gizl3ha](https://user-images.githubusercontent.com/15066/38219687-caec2464-36a4-11e8-9d59-023b3dcba9b3.jpeg)

Here's the updated version after #47.
