### ISSUE TITLE
Scale watermark placement by size of image

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/mustachify#45]
The watermark is always placed 25 px from the edge, a problem on smaller source images. The placement should be a percentage of the width/height of the source image.

**Comment by dryan** [comment]
Can you upload some images with this issue?

**Comment by dryan** [comment]
@iandees shouldn't be too hard to throw a thumbnail resize on the watermark of `image width - 50` to ensure this fits right?

Or should we just enforce a minimum image size?

**Comment by iandees** [comment]
We could do both:
- a minimum size on the input image of ~250px?
- thumbnail the watermark

**Comment by dryan** [comment]
Only because I could see us reusing this do I think we should do both.

**Comment by jillh510** [comment]
![oghsr9hotmiqldjks1n3iw](https://user-images.githubusercontent.com/2319837/38218906-31acddf0-3688-11e8-9d2f-baec69a59732.jpeg)

Watermark on this image would look better closer to the edges.

**Comment by dryan** [comment]
How about we make it 10px inset?

**Comment by iandees** [comment]
We were already thumbnailing the watermark image and I adjusted the inset to 10px in e53945b.
