### ISSUE TITLE
Need privacy policy

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/mustachify#46]
Depends on how long we're gonna store the images on S3.

**Comment by dryan** [comment]
Based on the current state of the project, I'd suggest holding them for 1 hour then rotating them out.

Since this is living in an iframe, we won't be publishing an explicit policy for users to read though, correct?

**Comment by dryan** [comment]
Also, if all of this is being sent to their AWS account, this isn't on us anyway. Though we should suggest a short lifecycle for them.

**Comment by dryan** [comment]
I setup a 1 day lifecycle for them, which turns out to be the shortest S3 supports.
