### ISSUE TITLE
Add extra image(s)

### ISSUE THREAD

**Issue by iandees** [RagtagOpen/mustachify#6]
We want the ability to add extra images over the top of the mustachified image. Maybe a logo like this one could go in the corner?

![image](https://user-images.githubusercontent.com/261584/34658899-aea14cf6-f3f8-11e7-9a1f-5261ba29fc2c.png)

**Comment by jillh510** [comment]
Overlay images from the campaign are here: https://drive.google.com/drive/folders/126C-jy7AOZ2BJiV1_Lp5hR11aOhlP5Di?usp=sharing

**Comment by schloo** [comment]
Yeah, I feel like lower right corner would be good. Not sure about ideal logo sizing yet... maybe once we have image sizing/aspect ration rules more defined.

**Comment by jillh510** [comment]
Any way we can use a semi-transparent image rather than one on a white rectangle?

**Comment by iandees** [comment]
This was fixed in #34.

We can definitely use a different image if we find one. I just found one on the Randy Bryce website.
